version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # Git submodules
    - run: git submodule sync --recursive
    - run: git submodule update --init --recursive --remote

    - run: docker build -t mewna/discord-backend:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM .

    - run: docker push mewna/discord-backend:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM